### PR TITLE
update grunt peerDep

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes https://github.com/gruntjs/grunt-docs/blob/master/Blog-2016-02-11-Grunt-1.0.0-rc1-released.md#peer-dependencies

### CODE REVIEW

**Comment by vladikoff** [comment]
@nDmitry Hello! We are releasing Grunt 1.0 soon and we still use this plugin in production everyday.

Could you please accept this change? I'm also happy to publish to npm and tag on github if you give me access. Thanks!

**Comment by nDmitry** [comment]
OK, I'll make a release with this soon. Can you tell why don't you use grunt-postcss? `autoprefixer` version here is well outdated.

**Comment by vladikoff** [comment]
@nDmitry I didn't get to it yet :). this plugin worked so well for several years now

**Comment by vladikoff** [comment]
Thanks for merging!!

**Comment by nDmitry** [comment]
Well, it's really easy https://github.com/nDmitry/grunt-postcss#how-to-migrate-from-grunt-autoprefixer

**Pull request merged**
