### PR TITLE
Fix grunt-autoprefixer blocking grunt when it finds no files

### LINKED ISSUE #115: Autoprefixer hangs on non existent filepath
Hello, I have this config:

```javscript
module.exports = function (ops) {
  return {
    options: {
      browsers: ['last 2 version', 'ie 9', 'opera 10']
    },
    main: {
      files: [
        {
          expand: true,
          cwd: '.tmp',
          src: ['styles/**/*.css'],
          dest: '.tmp'
        }
      ]
    },
    blocks: {
      files: [
        {
          expand: true,
          cwd: '.tmp',
          src: ['blocks/**/*.css'],
          dest: '.tmp'
        }
      ]
    }
  }
}
```
When blocks folder does not exist autoprefixer hangs on this task in 3.0.1, 3.0.0 is working fine.

### PR DESCRIPTION
**Pull request by 0xR**
Fixes #115

### CODE REVIEW

**Comment by nDmitry** [comment]
Thanks but I already fixed this, so closing this one.

**Comment by 0xR** [comment]
Yeah about that, it isn't fix. Your new code still assumes `this.files` is not empty. When it is empty the forEach loop is never called and `done()` is never called. My fix does fix it.

**Comment by nDmitry** [comment]
With what exactly config this.files can be empty?

I'm running grunt-autoprefixer with `src` property that maps nothing and get the following:

```
$ grunt autoprefixer
Running "autoprefixer:dist" (autoprefixer) task
>> No source files were found.

Done, without errors.
```

**Comment by 0xR** [comment]
``` javascript
    autoprefixer: {
      options: {
        browsers: ['> 5%', 'last 2 version', 'ie >= 9']
      },
      dist: {
        files: [
          {
            expand: true,
            cwd: '.tmp/css/',
            src: '**/*.css',
            dest: '.tmp/css/'
          }
        ]
      }
    },
```

**Comment by nDmitry** [comment]
Ok, let's add this condition too.

**Comment by nDmitry** [comment]
Thanks for the help!

**Pull request merged**
